title: Analogy-Angle II
description: A second edition of an interdisciplinary workshop co-located with ACL 2025. Analogy-Angle II will occur in Vienna, Austria on July 31 or August 1, 2025.
show_downloads: false
google_analytics: false
theme: jekyll-theme-dinky
github:
  is_user_page: false

